mongo:
  image: mongo
  ports:
   - "27017:27017"
  volumes:
    - /docker/mongodb:/data/db
  restart: always
application:
  build: .
  ports:
   - "3000:3000"
  environment:
   - MONGOLAB_URI=mongodb://mongo:27017/mydb
  links:
   - mongo
